// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Sj4sAlW8VehCZvpNo8CpZFo_bpdIkcI',
    appId: '1:541925138976:web:f7704541cc07ff280b9245',
    messagingSenderId: '541925138976',
    projectId: 'study-app-c215a',
    authDomain: 'study-app-c215a.firebaseapp.com',
    storageBucket: 'study-app-c215a.appspot.com',
    measurementId: 'G-4NTJGE28V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC28P4IMveQzmdGI3ixVfK30At2cVCneEY',
    appId: '1:541925138976:android:8ccfc335ca1129c30b9245',
    messagingSenderId: '541925138976',
    projectId: 'study-app-c215a',
    storageBucket: 'study-app-c215a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKBVRcF93lHbt2b2YGU5X_FGxKuI5uHyE',
    appId: '1:541925138976:ios:1772f6866595e0db0b9245',
    messagingSenderId: '541925138976',
    projectId: 'study-app-c215a',
    storageBucket: 'study-app-c215a.appspot.com',
    iosClientId: '541925138976-ks8lkk6fb2jovqiojbsl5hotbcs9t8fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKBVRcF93lHbt2b2YGU5X_FGxKuI5uHyE',
    appId: '1:541925138976:ios:9f2e2b8c6f2f65620b9245',
    messagingSenderId: '541925138976',
    projectId: 'study-app-c215a',
    storageBucket: 'study-app-c215a.appspot.com',
    iosClientId: '541925138976-6a0gnr4kfmjb2fi13ntiv8s5qsqi6hg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
